spring.application.name=flight-tracker
server.port=8080

# -----------------------------------
# OPENSKY API (Live GPS Data)
# -----------------------------------
# The exact URL for New Delhi airspace we tested in Postman
opensky.api.url=https://opensky-network.org/api/states/all?lamin=28.40&lomin=76.83&lamax=28.88&lomax=77.34
opensky.api.username=tusharsamaniya4956@gmail.com-api-client
opensky.api.password=bRfXQXKqc66o5gmG0h0puJzcZhB25tR0

# -----------------------------------
# AVIATIONSTACK API (Route Data)
# -----------------------------------
aviationstack.api.url=http://api.aviationstack.com/v1/flights
aviationstack.api.key=361a70e9953c7af809dbc8040c0419af
